"""Added resume and LinkedIn fields

Revision ID: 2b07e60fc5ac
Revises: 116e5d4d606c
Create Date: 2025-02-26 14:15:07.288229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b07e60fc5ac'
down_revision = '116e5d4d606c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedIn', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('linkedIn')
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
