"""Updated Project model: renamed location, added salary_min, salary_max, industry_other

Revision ID: 9652a7cfea4a
Revises: 433d7e8720ee
Create Date: 2025-03-15 15:05:46.250817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9652a7cfea4a'
down_revision = '433d7e8720ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_other', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('industry_other')

    # ### end Alembic commands ###
