"""Added modified_resume field to Project model

Revision ID: b3ff9d1bdc20
Revises: 9652a7cfea4a
Create Date: 2025-03-15 15:57:07.539699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ff9d1bdc20'
down_revision = '9652a7cfea4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_resume', sa.String(length=255), nullable=True))
        batch_op.drop_column('resume')
        batch_op.drop_column('linkedIn')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('resume')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedIn', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('modified_resume')

    # ### end Alembic commands ###
